name: make android release

on:
  push:
    tags:
      - '*'

jobs:
  publish-lts-on-linux:
    name: android lts on linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: run the build script
        run: ./android.sh --lts --disable-arm-v7a-neon --enable-cpu-features
      - name: copy build artifact
        run: mv prebuilt/bundle-android-aar-lts/ffmpeg-kit/ffmpeg-kit.aar aniyomi-ffmpeg-kit-${{ github.ref_name }}.aar
      - name: release artifact
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ github.ref_name }}
          name: aniyomi-ffmpeg-kit ${{ github.ref_name }}
          body: |
            library version ${{ github.ref_name }}
          files: |
            aniyomi-ffmpeg-kit-${{ github.ref_name }}.aar
          draft: false
          prerelease: false
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
